#!/system/bin/busybox sh
# make sure to hardcode moddir as we wont be inside 
# root manager env anymore when cronjobs are ran
MODDIR="/data/adb/modules/sensitive_props"
# Using util_functions.sh
source $MODDIR/util_functions.sh

# Periodically delete LineageOS and EvolutionX props
hexpatch_deleteprop "lineage"
hexpatch_deleteprop "evolution"
hexpatch_deleteprop "crdroid"
hexpatch_deleteprop "crDroid"
hexpatch_deleteprop "aospa"
hexpatch_deleteprop "LSPosed"
hexpatch_deleteprop "aicp"
hexpatch_deleteprop "arter97"
hexpatch_deleteprop "blu_spark"
hexpatch_deleteprop "cyanogenmod"
hexpatch_deleteprop "deathly"
hexpatch_deleteprop "elementalx"
hexpatch_deleteprop "elite"
hexpatch_deleteprop "franco"
hexpatch_deleteprop "hadeskernel"
hexpatch_deleteprop "morokernel"
hexpatch_deleteprop "noble"
hexpatch_deleteprop "optimus"
hexpatch_deleteprop "slimroms"
hexpatch_deleteprop "sultan"
hexpatch_deleteprop "aokp"
hexpatch_deleteprop "bharos"
hexpatch_deleteprop "calyxos"
hexpatch_deleteprop "calyxOS"
hexpatch_deleteprop "divestos"
hexpatch_deleteprop "emteria.os"
hexpatch_deleteprop "grapheneos"
hexpatch_deleteprop "indus"
hexpatch_deleteprop "iodéos"
hexpatch_deleteprop "kali"
hexpatch_deleteprop "nethunter"
hexpatch_deleteprop "omnirom"
hexpatch_deleteprop "paranoid"
hexpatch_deleteprop "replicant"
hexpatch_deleteprop "resurrection"
hexpatch_deleteprop "remix"
hexpatch_deleteprop "pixelexperience"
hexpatch_deleteprop "shift"
hexpatch_deleteprop "volla"
hexpatch_deleteprop "icosa"
hexpatch_deleteprop "kirisakura"
hexpatch_deleteprop "infinity"
hexpatch_deleteprop "Infinity"

echo $(date) >> /debug_ramdisk/sensitive_props.log
